const router = require('express').Router();
const auth = require('../middlewares/authMiddleware');
const controller = require('../controllers/interviewController');
router.use(auth);
router.post('/applications/:id/schedule', controller.schedule);
router.post('/applications/:id/start', controller.start);
router.post('/applications/:id/finish', controller.finish);
router.post('/applications/:id/cancel', controller.cancel);
router.get('/company', controller.listCompany);
router.get('/candidate', controller.listCandidate);
router.get('/applications/:id/interview/recruiter', controller.getByApplication);
router.get('/applications/:id/interview', controller.getByApplicationPublic);
module.exports = router;
